# Generated by Django 3.2.12 on 2022-04-04 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='location',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='hotel',
            name='location_url',
            field=models.URLField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='hotel',
            name='main_image',
            field=models.ImageField(default='', upload_to='hotel/images'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
