# Generated by Django 3.2.12 on 2022-04-04 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_auto_20220405_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='location_url',
            field=models.URLField(default='', max_length=500),
        ),
    ]
