# Generated by Django 3.2.12 on 2022-04-07 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_alter_hotel_location_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='category',
            field=models.CharField(default='', max_length=100),
        ),
    ]
