# Generated by Django 3.2.12 on 2022-04-18 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_hotel_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('desc_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('phone', models.CharField(default='', max_length=100)),
                ('desc', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
